# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-case-conflict
          - id: check-docstring-first
          - id: debug-statements
          - id: detect-private-key
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: forbid-new-submodules
          - id: end-of-file-fixer

      # -   id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
          - id: mypy
            args: [--ignore-missing-imports]

    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black

    - repo: https://github.com/asottile/blacken-docs
      rev: v1.8.0
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==20.8b1]

    - repo: https://gitlab.com/pycqa/flake8
      rev: "3.8.3"
      hooks:
          - id: flake8
